### ISSUE TITLE
Memory leak with SpoutCam.ax in OBS studio

### ISSUE THREAD

**Issue by phields** [keijiro/KlakSpout#57]

**Comment by keijiro** [comment]
Could you provide details?

**Comment by phields** [comment]
https://github.com/leadedge/SpoutCam
I use this project's with KlakSpout in OBS studio
The source has picture output, but the OBS's memory keeps going up.
![image](https://user-images.githubusercontent.com/31947421/91799105-f0d52880-ec58-11ea-8052-3afa6070ce85.png)

**Comment by phields** [comment]
There is no memory leak in unity processes.
This will only happen in applications that use a virtual camera, speculation is that this may be caused by updating a new version of the SpoutCam.ax file.
The same things happening in the OpenGL branch.
https://github.com/leadedge/SpoutCam/tree/OpenGL

**Comment by keijiro** [comment]
I think I can do nothing with this issue. Someone should fix it on the OBS side.

**Comment by phields** [comment]
If I use the original SpoutSender, the memory leak issue doesn't happen.
I tried upgrading and compiling a new version of the SpoutSDK, but the problem persists, probably due to the fact that I commented out this code (Unity will crash if I don't remove it)
![image](https://user-images.githubusercontent.com/31947421/91799830-70172c00-ec5a-11ea-80ad-918fa9048f97.png)

**Comment by keijiro** [comment]
> If I use the original SpoutSender, the memory leak issue doesn't happen.

Do you mean SpoutSender v2.007? If so, how about SpoutSender v2.006?

If the issue reproduces with SpoutSender v2.006, there might be a backward compatibility issue in the Spout SDK. It should be reported to the Spout devs.

**Comment by phields** [comment]
I just tested the problem on Spout version 2.005 and there is a memory leak.
This is indeed an official backward compatibility issue, thank you for your time!
