### ISSUE TITLE
Spouts do not function in Unity 2021.2.0b2 standalone builds

### ISSUE THREAD

**Issue by MrMahgu** [keijiro/KlakSpout#72]
I can not get any spout senders or receivers to function once I export my build via IL2CPP or MONO.  In my case -- using render textures.  

All is working in play mode in editor.

Steps to produce:

Unity 2021.2.0b2 -> New Project
Add scoped registries
Install HDRP 12
Install KlakSpout 2.0.1

Add RenderTexture
Configure RenderTexture
Add GameObject
Add Spout Sender
Configure Spout Sender with RenderTexture and Name
Build
Run Build -> No spout activity

Windows 10, x64.

**Comment by keijiro** [comment]
Thanks for reporting it. I found that conditional compilation I added in the last update (v2.0.1) caused this issue. I fixed it in v2.0.2.

**Comment by keijiro** [comment]
I'm closing this issue as resolved. Please feel free to reopen it if it still reproduces.

**Comment by antoniohof** [comment]
I still dont get spout output when in standalone builds :/ even with the new version.

**Comment by antoniohof** [comment]
I dont get image when using in standalone builds,
spout output appears but is empty.


 maybe you have an idea of whats going on?

**Comment by antoniohof** [comment]
Im using HDRP, Spout sender set to Camera and unity 2020.03.14f1

**Comment by keijiro** [comment]
@antoniohof Could you post it as a new issue and attach a minimal project that reproduces the issue?
